Add ABAP Language Version
abapGit/docs.abapgit.org pull request #184
Opened 2023-11-09 22:10 UTC by mbtools

After #183 

Ref https://github.com/abapGit/abapGit/issues/6154

2023-11-10 06:45 UTC, larshp commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
for any it should not serialize the ALV, as its overwritten on import anyhow?

2023-11-10 06:45 UTC, larshp commented on src/user-guide/reference/abap-lanuage-version.md
> +If a specific ABAP language version is defined, then all objects  in the repository must adhere to this ABAP language version. If not, you will receive an error message.
when the repository is serialized?

2023-11-10 06:47 UTC, larshp commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will **not* be part of the metadata of each object.
in this case the code is intended for one platform, so I'd expect it to be serialized here?

2023-11-10 06:49 UTC, larshp commented on src/user-guide/reference/abap-lanuage-version.md
> +This will ensure, that only objects compatible with BTP will be included in your project.
suggest linking https://github.com/abaplint/abaplint/blob/main/docs/getting_started.md for how to check compatibility

2023-11-10 06:50 UTC, larshp requested changes
see comments

2023-11-10 16:40 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
then we would get diffs for all existing repos:
https://github.com/abapGit-tests/PROG/blob/main/src/zag_unit_test.prog.xml#L10
https://github.com/abapGit-tests/CLAS/blob/main/src/zcl_ag_unit_test.clas.xml#L12

2023-11-10 16:40 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +If a specific ABAP language version is defined, then all objects  in the repository must adhere to this ABAP language version. If not, you will receive an error message.
need to test this

2023-11-10 16:41 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will **not* be part of the metadata of each object.
we could be there's no need to serialize it since we know what it is

2023-11-10 16:44 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +This will ensure, that only objects compatible with BTP will be included in your project.
👍 done

2023-11-12 07:44 UTC, larshp commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
hmm, will get that after import to an environment with different ALV anyhow?

2023-11-12 12:11 UTC, larshp commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
we can consider excluding it in AFF

2023-11-14 23:24 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
import into another ALaV environment tries to set the ALaV of the target system. If there are no errors, you will indeed get diffs. Nothing changed with this. 

AFF is already removing it:

https://github.com/abapGit/abapGit/blob/0cbbc5bbfd3f8344e8e675b35432968c210dcb54/src/objects/aff/zcl_abapgit_object_common_aff.clas.abap#L133

2023-11-14 23:24 UTC, mbtools commented
I will make a table for the different combinations.

2023-11-15 09:17 UTC, schneidermic0 approved these changes
Thanks, @mbtools for the documentation of ABAP language version in abapGit.

Look quite good to me. 👍 I have just added some comments

2023-11-15 09:17 UTC, schneidermic0 commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
> AFF is already removing it:

This was requested by @larshp ;)

But this means the information is lost and you don't have an "Object-specific ABAP Language Version" as mentioned in the table above.

2023-11-15 09:17 UTC, schneidermic0 commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will **not* be part of the metadata of each object.
I agree with @mbtools. I understood abapGit doesn't serialize the ABAP language version, but specifies for the whole repository.

But this means we either have no object-specific ABAP language version or abapGit needs to serialize it when the setting is "Any" see discussion above.

2023-11-15 09:17 UTC, schneidermic0 commented on src/user-guide/reference/abap-lanuage-version.md
> +This will ensure, that users will not be able to install the project on BTP.
@ThomasPloski Is this the case? I think (at least as of now) on SAP BTP, ABAP environment the import will set all objects to ABAP language version 5. 

If so, should this be changed having the new setting and the project is set to "Standard ABAP"?

2023-11-15 13:53 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
to be consistent, if the repo is set to "Any", then AFF should serialize ALaV

2023-11-16 08:21 UTC, schneidermic0 commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
I think I have no strong opinion. Or even from pure AFF perspective I would like to have the ABAP language version serialized. ;)

> to be consistent, if the repo is set to "Any", then AFF should serialize ALaV

This would mean, if my understanding is correct, as soon as you import a repository to SAP BTP, afterwards all objects are set to ABAP language version "Cloud Development". If the repo is set to "Any" you might get a large diff. 

I think this is also related to my comment here: https://github.com/abapGit/docs.abapgit.org/pull/184#discussion_r1393888938

2023-11-16 09:13 UTC, larshp commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
perhaps we should add another option?

2023-11-16 15:38 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
We might need "not serialized", too. it's still experimental 😄  let's continue discussion in https://github.com/abapGit/abapGit/issues/6154

2023-11-27 18:40 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will be part of the metadata of each object.
added "ignore" option

2023-11-27 18:41 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +This will ensure, that users will not be able to install the project on BTP.
added "ignore" option

2023-11-30 15:30 UTC, schneidermic0 reviewed
Thanks, for the update. I have just some small comments.

2023-11-30 15:30 UTC, schneidermic0 commented on src/user-guide/reference/abap-lanuage-version.md
> +There are four possible [settings](./repo-settings/dot-abapgit.html) for defining how the ABAP language version is handled by abapGit:
```suggestion
There are five possible [settings](./repo-settings/dot-abapgit.html) for defining how the ABAP language version is handled by abapGit:
```

2023-11-30 15:30 UTC, schneidermic0 commented on src/user-guide/reference/abap-lanuage-version.md
> +The ABAP language version of an object might conflict with the setting of the root package of the repository (which is limited by the system environment and software component of the package). This m
As far as I know, during the syntax check the ABAP language version the object is considered (not the ABAP language version of the package or software component). 
There are just an ATC checks you can use to ensure all objects of the package/software component have a consistent ABAP language version.

2023-11-30 15:31 UTC, schneidermic0 commented
I think the setting "Any" has not been supported by the AFF object super class, yet. Currently, it removes the ABAP language version always.

2023-11-30 16:34 UTC, mbtools commented
I changed the AFF logic already to remove ALaV only in "ignore mode"

https://github.com/abapGit/abapGit/blob/931e4c1006f4fa3947718686966b06579b4d8b47/src/objects/aff/zcl_abapgit_object_common_aff.clas.abap#L620-L623

2023-11-30 16:42 UTC, mbtools commented on src/user-guide/reference/abap-lanuage-version.md
> +The ABAP language version of an object might conflict with the setting of the root package of the repository (which is limited by the system environment and software component of the package). This m
Thanks. Changed

2023-11-30 19:45 UTC, schneidermic0 commented
> I changed the AFF logic already to remove ALaV only in "ignore mode"

Ah, good to know. 👍 But one more question: In the documentation it is stated  the ABAP LV is also **not** serialized if the repository is set to a specific version:

https://github.com/abapGit/docs.abapgit.org/blob/9a7d8c154960e695d9c3d48fc63c8568de2ec33f/src/user-guide/reference/abap-lanuage-version.md?plain=1#L79

I guess we either need to adapt documentation or AFF logic should be remove ABAP LV only if the setting is "Any". What do you think?

2023-12-01 07:07 UTC, schneidermic0 commented
Yes, this is fine for me :)

2023-12-01 07:09 UTC, schneidermic0 commented on src/user-guide/reference/abap-lanuage-version.md
> +When serializing objects, the ABAP language version will **not* be part of the metadata of each object.
As far as I understood, ABAP LV shall be serialized (except in the "ignore" setting).

```suggestion
When serializing objects, the ABAP language version will be part of the metadata of each object.
```

2023-12-05 20:29 UTC, mbtools commented
I added a section about supported object types. This should be good to go

2023-12-06 07:28 UTC, larshp commented on src/user-guide/reference/abap-lanuage-version.md
> +So far, abapGit handles ABAP language version only for a limited set of object types. See Spported Object Types, below.
```suggestion
So far, abapGit handles ABAP language version only for a limited set of object types. See Supported Object Types, below. 
```

2023-12-06 07:54 UTC, albertmink reviewed
Hmm, there are still some ABAP **L**anguage **V**ersions around in the PR, for which I provided SUGGESTIONS. I didn't check the entire files, so maybe there are some left overs there as well.

2023-12-06 07:54 UTC, albertmink commented on src/user-guide/reference/abap-language-version.md
> +If you set the ABAP Language Version to "Ignore" it will not be serialized. This avoids diffs due to variations in development and target environments.
```suggestion
If you set the ABAP language version to "Ignore" it will not be serialized. This avoids diffs due to variations in development and target environments. 
```

2023-12-06 07:54 UTC, albertmink commented on src/user-guide/repo-settings/dot-abapgit.md
> +You can define how abapGit handles the ABAP Language Version of objects in a repository. The default setting is "Any" which allows objects of any ABAP Language Version to be included in your reposito
```suggestion
You can define how abapGit handles the ABAP language version of objects in a repository. The default setting is "Any" which allows objects of any ABAP language version to be included in your repository. The other settings will limit the type of objects to exactly one of the ABAP language versions. For more details, see [ABAP Language Version](/user-guide/reference/abap-language-version.md).
```

2023-12-06 07:54 UTC, albertmink commented on src/user-guide/reference/abap-language-version.md
> +Ignore                     | ABAP Language Version not serialized
```suggestion
Ignore                     | ABAP language version not serialized
```

2023-12-06 07:54 UTC, albertmink commented on src/user-guide/reference/abap-language-version.md
> +Any (default)              | Object-specific ABAP Language Version
```suggestion
Any (default)              | Object-specific ABAP language version
```

2023-12-06 15:55 UTC, mbtools commented
Thanks for the corrections 👍

2023-12-07 08:29 UTC, schneidermic0 approved these changes
Looks good to me. Just one more question regarding supported object types but we can add these later.

2023-12-07 11:02 UTC, larshp commented on src/user-guide/reference/abap-language-version.md
> +`CLAS`, `DEVC`, `FUGR`, `INTF`, `PROG`
suggest adding another column in https://docs.abapgit.org/user-guide/reference/supported.html with a checkmark if its AFF

2023-12-07 12:52 UTC, schneidermic0 commented on src/user-guide/reference/abap-language-version.md
> +`CLAS`, `DEVC`, `FUGR`, `INTF`, `PROG`
As mentioned before. Fine for me if this is handled separately. 👍

2023-12-07 14:31 UTC, mbtools commented
@larshp you just need to update your review 😉 🙏

2023-12-07 15:02 UTC, larshp approved these changes

2023-12-07 15:31 UTC, merged

2023-12-07 15:48 UTC, schneidermic0 commented
Thanks @mbtools for your efforts 👍