Updating text and screenshots as per the changes in #6759
abapGit/docs.abapgit.org pull request #234
Opened 2024-06-09 00:32 UTC by francisco-milan

2024-06-09 05:17 UTC, larshp requested changes

2024-06-09 05:17 UTC, larshp commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
we want the screenshots in real git, ie. the /img/ folder

2024-06-09 05:17 UTC, larshp commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
easiest is to start vscode, and do the editing from there

2024-06-09 17:21 UTC, francisco-milan commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
Hi @larshp,

    It looks like I don't have access to the /img/ folder
![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/4e316ca8-6399-4763-84f4-e9a646ed17ba)

2024-06-09 19:20 UTC, mbtools commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
Images are stored in `https://github.com/abapGit/docs.abapgit.org/tree/main/src/.vuepress/public/img`

You can then refer to them, for example, like this on a doc page:

`![abapGit](/img/abapgit_1_99_0.png)`

2024-06-09 20:39 UTC, francisco-milan commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
Thanks @mbtools,

   I tried to upload a new file with a screenshot...

![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/546185cb-a6d3-4cfa-8e56-c09d4b1945c6)

... but I got this message:

![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/4ec884ae-deb6-4b4c-8f58-128b9dbb93ab)

2024-06-10 04:23 UTC, larshp commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
choose the right branch?

2024-06-10 06:30 UTC, mbtools commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
you're trying to upload to the original repo but the changes need to be in your fork 😉

2024-06-10 17:12 UTC, larshp commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
nice, then replace these with the img

2024-06-10 17:21 UTC, francisco-milan commented on src/user-guide/setup/settings-global.md
> +![image](https://github.com/abapGit/docs.abapgit.org/assets/36721657/d9d2793d-cc38-4c55-adf0-792b879dddde)
Got it! Thanks a lot for your help, now the screenshots and the links are updated.

Best,

Francisco Milán.

2024-06-11 05:15 UTC, larshp approved these changes

2024-06-11 05:43 UTC, merged